echo "Afrikaans:    Hello Wêreld!"
echo "Albanian:     Përshendetje Botë!"
echo "Amharic:      ሰላም ልዑል!"
echo "Arabic:       مرحبا بالعالم!"
echo "Armenian:     Բարեւ աշխարհ!"
echo "Basque:       Kaixo Mundua!"
echo "Belarussian:  Прывітанне Сусвет!"
echo "Bengali:      ওহে বিশ্ব!"
echo "Bulgarian:    Здравей свят!"
echo "Catalan:      Hola món!"
echo "Chichewa:     Moni Dziko Lapansi!"
echo "Chinese:      你好世界！"
echo "Croatian:     Pozdrav svijete!"
echo "Czech:        Ahoj světe!"
echo "Danish:       Hej Verden!"
echo "Dutch:        Hallo Wereld!"
echo "English:      Hello World!"
echo "Estonian:     Tere maailm!"
echo "Finnish:      Hei maailma!"
echo "French:       Bonjour monde!"
echo "Frisian:      Hallo wrâld!"
echo "Georgian:     გამარჯობა მსოფლიო!"
echo "German:       Hallo Welt!"
echo "Greek:        Γειά σου Κόσμε!"
echo "Hausa:        Sannu Duniya!"
echo "Hebrew:       שלום עולם!"
echo "Hindi:        नमस्ते दुनिया!"
echo "Hungarian:    Helló Világ!"
echo "Icelandic:    Halló heimur!"
echo "Igbo:         Ndewo Ụwa!"
echo "Indonesian:   Halo Dunia!"
echo "Italian:      Ciao mondo!"
echo "Japanese:     こんにちは世界！"
echo "Kazakh:       Сәлем Әлем!"
echo "Khmer:        សួស្តី​ពិភពលោក!"
echo "Kyrgyz:       Салам дүйнө!"
echo "Lao:          ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!"
echo "Latvian:      Sveika pasaule!"
echo "Lithuanian:   Labas pasauli!"
echo "Luxemburgish: Moien Welt!"
echo "Macedonian:   Здраво свету!"
echo "Malay:        Hai dunia!"
echo "Malayalam:    ഹലോ വേൾഡ്!"
echo "Mongolian:    Сайн уу дэлхий!"
echo "Myanmar:      မင်္ဂလာပါကမ္ဘာလောက!"
echo "Nepali:       नमस्कार संसार!"
echo "Norwegian:    Hei Verden!"
echo "Pashto:       سلام نړی!"
echo "Persian:      سلام دنیا!"
echo "Polish:       Witaj świecie!"
echo "Portuguese:   Olá Mundo!"
echo "Punjabi:      ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!"
echo "Romanian:     Salut Lume!"
echo "Russian:      Привет мир!"
echo "Scots Gaelic: Hàlo a Shaoghail!"
echo "Serbian:      Здраво Свете!"
echo "Sesotho:      Lefatše Lumela!"
echo "Sinhala:      හෙලෝ වර්ල්ඩ්!"
echo "Slovenian:    Pozdravljen svet!"
echo "Spanish:      ¡Hola Mundo!"
echo "Sundanese:    Halo Dunya!"
echo "Swahili:      Salamu Dunia!"
echo "Swedish:      Hej världen!"
echo "Tajik:        Салом Ҷаҳон!"
echo "Thai:         สวัสดีชาวโลก!"
echo "Turkish:      Selam Dünya!"
echo "Ukrainian:    Привіт Світ!"
echo "Uzbek:        Salom Dunyo!"
echo "Vietnamese:   Chào thế giới!"
echo "Welsh:        Helo Byd!"
echo "Xhosa:        Molo Lizwe!"
echo "Yiddish:      העלא וועלט!"
echo "Yoruba:       Mo ki O Ile Aiye!"
echo "Zulu:         Sawubona Mhlaba!"
